### ISSUE TITLE
Missing tooltips for guiding users

### ISSUE THREAD

**Issue by Jiab77** [messede-degod/SF-UI#16]
It would be nice to add some tooltips over the icons to help users to understand their meaning / use without having to click on it.

![image](https://github.com/messede-degod/SF-UI/assets/9881407/701d5c14-567a-404c-8bbd-1a1a74bb585d)
![image](https://github.com/messede-degod/SF-UI/assets/9881407/88bcb53d-257b-46bb-945e-7ff70d18fe3b)

Something like that:

![image](https://github.com/messede-degod/SF-UI/assets/9881407/1861fb33-f0f7-4dc3-a5f1-c1b90509d82d)

But in a better way 😅 

I've made this from the console but maybe I've guessed the meaning wrongly:

![image](https://github.com/messede-degod/SF-UI/assets/9881407/6d03ceb5-1a57-4c59-b3d1-323a65b5cac8)

But if that's correct, I can try to make a pull request and add it to the main code.

**Comment by messede-degod** [comment]
Sure thing looks good 👍, go ahead

**Comment by messede-degod** [comment]
Yes, that is correct, since it was very trivial i've made those changes here : ae69acb67acc964c06e185680a1e19b08f54ef71, thank you for looking out 👍

**Comment by Jiab77** [comment]
@messede-degod, You're very welcome, I'm glad to help :)
